name: Create Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Put fixed version and cache bust parameters
        run: |
          # Put a fixed version
          sed -i -E 's/(<!--VERSION-->Version: ).+/\1'"${{ github.ref_name }}"'/' index.html
          # Cache bust top js and css
          VERSION="${{ github.ref_name }}"
          ESCAPED_VERSION=$(printf '%s' "$VERSION" | sha1sum | cut -c1-8)
          find . -name '*.html' -print0 | xargs -0 sed -E -i'' 's/\.(css|js)(\?[^"]*)?">/.\1?'$ESCAPED_VERSION'">/g'

      - name: Create custom tarball
        run: |
         tar -czf ${{ runner.temp }}/sentinel-${{ github.ref_name }}.tar.gz \
            --transform "s,^,sentinel-${{ github.ref_name }}/," \
            *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: |
            ### About
            
            This is an automated release.

            ### Changelog
          draft: true
          prerelease: false
          generate_release_notes: true
          files: ${{ runner.temp }}/sentinel-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
